$(document).ready(function(){
    $('.gerText').click(function(){
        console.log($('.content').text());
    })
    $('.getHtml').click(function(){
        console.log($('.content').html());
    })
    $('.getVal').click(function(){
        console.log($('.weather').val());
    })
    $('.setText').click(function(){
        console.log($('.content').html());
    })
})